### PR TITLE
Update pyproject.toml with flask-wtf>1.1

### PR DESCRIPTION
**Pull request by oegedijk**
Updates the dependency of flask-wtf to deal with issue mentioned in #33

### CODE REVIEW

**Review by cuducos — APPROVED** [review]
Many thanks! I'll try to merge and publish a release today or tomorrow : )

**Comment by oegedijk** [comment]
Also can probably get rid of support for python 3.6 and 3.7. And maybe add 3.9 and 3.10 to the test matrix:  https://github.com/flask-extensions/Flask-SimpleLogin/blob/main/.github/workflows/tests.yaml

**Comment by cuducos** [comment]
BTW don't worry about Python 3.6. It has reached its [end-of-life](https://devguide.python.org/versions/), so no problem to drop support for Python 3.6 moving forward.

**Comment by cuducos** [comment]
> Also can probably get rid of support for python 3.6 and 3.7. And maybe add 3.9 and 3.10 to the test matrix

I'd keep 3.7 (it hasn't reached end-of-life). Beyond that, adding 3.9 and 3.10 is a great contribution : )

**Comment by cuducos** [comment]
If you get to change that before I do, we also need to update the supported versions on `pyproject.toml`:

https://github.com/flask-extensions/Flask-SimpleLogin/blob/b6bfd358fddb406a22cfda46eb2e870dca644f85/pyproject.toml#L12-L15

**Pull request merged**
